http:
  address: "0.0.0.0:8081"

kafka:
  brokers:
    - "kafka:29092"
  topic: "orders"
  group_id: "order-service"

database:
  host: "db"
  port: 5432
  user: "user"
  password: "12345"
  dbname: "postgres_db"
  sslmode: "disable"

cache_ttl: "10m"