http:
  address: "0.0.0.0:8081"

kafka:
  brokers:
    - "broker:9092"
  topic: "orders"
  group_id: "order-service"

database:
  host: "db"
  port: 5432
  user: "user"
  password: "12345"
  dbname: "db"
  sslmode: "disable"